version: "3"
services:
  laravel:
    image: dagume/nginx-php7.3-ideasoft:latest
    volumes:
      - .:/var/www/html
    depends_on:
      - pgsql
    ports:
      - 8086:80
  pgsql:
    image: postgres:10
    environment:
      POSTGRES_USER: laravel_admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel_db     
    volumes:
      - postgres_database_sql:/var/lib/postgresql/data           
    ports:
      - 5440:5432

volumes:
  postgres_database_sql:
      external: true